# URL de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/bd_palomino?useSSL=false&serverTimezone=UTC

# Credenciales MySQL locales
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT
app.jwt.secret=palomino-jwt-secreto-cambiar-antes-de-produccion-123456789
app.jwt.expiration-ms=86400000
